version: '3.8'

services:
  iptv-proxy:
    build:
      context: .
      dockerfile: Dockerfile-iptv
    container_name: iptv-nginx-proxy
    ports:
      - "4000:3000"
    environment:
      - IPTV_USER=${IPTV_USER}
      - IPTV_PASS=${IPTV_PASS}
    env_file:
      - .env