services:
  walactv-proxificaurl:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: [ "python", "proxificaUrl.py" ]
    env_file:
      - path: .env

  walactv-new-scrapper:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: [ "python", "main2.py" ]
    env_file:
      - path: .env

  walactv-futboltv:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: [ "python", "main.py" ]
    env_file:
      - path: .env

  #PARA LOCAL
  #  acestream-http-proxy:
  #    image: ghcr.io/martinbjeldbak/acestream-http-proxy
  #    container_name: acestream-http-proxy
  #    ports:
  #      - 6878:6878
  #    environment:
  #      - ALLOW_REMOTE_ACCESS=yes

  acestream-arm:
    image: jopsis/acestream:arm64
    container_name: acestream-arm
    privileged: true
    restart: unless-stopped
    platform: linux/arm64
    environment:
      TZ: Europe/Madrid
      ALLOW_REMOTE_ACCESS: "yes"
    volumes:
      - ./acestream-config:/acestream.engine
    labels:
      # --- Traefik Integration ---
      - "traefik.enable=true"

      # Router HTTP (redirección a HTTPS)
      - "traefik.http.routers.acestream-http.rule=Host(`acestream.walerike.com`)"
      - "traefik.http.routers.acestream-http.entrypoints=web"
      - "traefik.http.routers.acestream-http.middlewares=acestream-redirect"

      # Router HTTPS
      - "traefik.http.routers.acestream.rule=Host(`acestream.walerike.com`)"
      - "traefik.http.routers.acestream.entrypoints=websecure"
      - "traefik.http.routers.acestream.tls=true"
      - "traefik.http.routers.acestream.tls.certresolver=myresolver"

      # Service
      - "traefik.http.services.acestream.loadbalancer.server.port=6878"

      # Middlewares
      - "traefik.http.middlewares.acestream-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.acestream-redirect.redirectscheme.permanent=true"

    networks:
      - dokploy-network




#  acestream-arm2:
#    image: jopsis/acestream:arm64
#    container_name: acestream-arm2
#    platform: linux/arm64          # <-- Emulación ARM64 en host AMD64
#    privileged: true
#    restart: unless-stopped
#    ports:
#      - "6878:6878"                # AceStream engine HTTP
#      - "8621:8621"                # AceStream web interface
#    environment:
#      - TZ=Europe/Madrid
#      - ACESTREAM_REMOTE=yes        # Permite acceso remoto
#    volumes:
#      - ./acestream-config:/acestream.engine

networks:
  dokploy-network:
    external: true
