version: '3.8'

services:
  iptv-proxy:
    build:
      context: ..
      dockerfile: docker/Dockerfile-iptv
    container_name: proxy-iptv
    env_file:
      - .env
    ports:
      - "4000:4000"

    dns:
      - 8.8.8.8
      - 8.8.4.4

    restart: unless-stopped

    networks:
      - dokploy-network

    labels:
      - "traefik.enable=true"

      # --- HTTPS Router (Entrada segura) ---
      - "traefik.http.routers.iptv-v2.rule=Host(`iptv.walerike.com`)"
      - "traefik.http.routers.iptv-v2.entrypoints=websecure"
      - "traefik.http.routers.iptv-v2.tls=true"
      - "traefik.http.routers.iptv-v2.tls.certresolver=letsencrypt"

      # --- SERVICE IMPORTANTE (Obligatorio para resolver el conflicto) ---
      # Esto fuerza a Traefik a usar este contenedor en el puerto 4000
      - "traefik.http.services.iptv-v2.loadbalancer.server.port=4000"

      # --- HTTP Router (Redirecci√≥n) ---
      - "traefik.http.routers.iptv-v2-http.rule=Host(`iptv.walerike.com`)"
      - "traefik.http.routers.iptv-v2-http.entrypoints=web"
      - "traefik.http.routers.iptv-v2-http.middlewares=redirect-https"

      # --- Middleware (Definido localmente) ---
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      -
  nginx-images:
    image: nginx:alpine
    container_name: nginx-images
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.images.rule=Host(`static.walerike.com`)"
      - "traefik.http.routers.images.entrypoints=websecure"
      - "traefik.http.routers.images.tls=true"
      - "traefik.http.routers.images.tls.certresolver=letsencrypt"
      - "traefik.http.services.images.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true