version: '3.8'

services:
  iptv-proxy:
    build:
      context: ..
      dockerfile: docker/Dockerfile-iptv
    container_name: proxy-iptv

    ports:
      - "4000:3000"

    dns:
      - 8.8.8.8
      - 8.8.4.4

    restart: unless-stopped

    networks:
      - dokploy-network

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iptv-v2-https.rule=Host(`iptv.walerike.com`)"
      - "traefik.http.routers.iptv-v2-https.entrypoints=websecure"
      - "traefik.http.routers.iptv-v2-https.tls=true"
      - "traefik.http.routers.iptv-v2-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.iptv-v2-http.rule=Host(`iptv.walerike.com`)"
      - "traefik.http.routers.iptv-v2-http.entrypoints=web"
      - "traefik.http.routers.iptv-v2-http.middlewares=redirect-https@docker"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"

networks:
  dokploy-network:
    external: true