version: '3.8'

services:
  iptv-proxy:
    build:
      context: .
      dockerfile: Dockerfile-iptv
    container_name: iptv-nginx-proxy
    ports:
      - "4000:3000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped