version: '3.8'

services:
  iptv-proxy:
    build:
      context: .
      dockerfile: Dockerfile-iptv
    container_name: iptv-nginx-proxy
    ports:
      - "4000:3000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iptv-proxy.rule=Host(`iptv.walerike.com`)"
      - "traefik.http.routers.iptv-proxy.entrypoints=websecure"
      - "traefik.http.routers.iptv-proxy.tls.certresolver=letsencrypt"
      - "traefik.http.services.iptv-proxy.loadbalancer.server.port=3000"
      - "traefik.http.services.iptv-proxy.loadbalancer.server.scheme=http"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true